theme: jekyll-theme-minimal
url: 'https://alexandradi.github.io/'
baseurl: 'Alex_Portfolio/'
#logo: https://github.com/AlexandraDI/ALMA/blob/master/src/main/resources/static/avatars/AvatarMaker.png?raw=true
logo: https://github.com/AlexandraDI/ALMA/blob/master/src/main/resources/static/avatars/new_me_cropped.png?raw=true
title: [Alexandra_Gianzina]
description: [M.Sc in Artificial Intelligence \nB.Sc in Computer Science]
# show_downloads: [false]
markdown: kramdown
github:
  zip_url: https://github.com/AlexandraDI/Autonomous_Robotic_Systems
