theme: jekyll-theme-minimal
url: 'https://alexandradi.github.io/'
baseurl: 'Alex_Portfolio/'
#logo: https://github.com/AlexandraDI/ALMA/blob/master/src/main/resources/static/avatars/AvatarMaker.png?raw=true
logo: https://github.com/AlexandraDI/Connections/tree/master/pics/me_HD_no_background.png?raw=true
title: [Alexandra_Gianzina]
description: [M.Sc in Artificial Intelligence]
# show_downloads: [false]
markdown: kramdown
github:
  zip_url: https://github.com/AlexandraDI/Autonomous_Robotic_Systems
