theme: jekyll-theme-minimal
logo: https://github.com/AlexandraDI/ALMA/blob/master/src/main/resources/static/avatars/AvatarMaker.png?raw=true
# title: [Alexandra Portfolio]
show_downloads: [true]
github:
  zip_url: https://github.com/AlexandraDI/Autonomous_Robotic_Systems
